QUESTIONS = [
    {
        "id": "Q1",
        "question": "What is the default value and type of `retry_backoff_ms` on `Client.send()`?",
        "correct_sdk_version": "v3",
        "correct_page_id": "client-send",
        "correct_source_file": "v3/client-send.md",
        "correct_section": "Parameters",
        "known_answer": "int, default 250 (v3). Note: v2 default was 100 -- this is the version-collision question used for the metadata filter demo.",
        "depends_on": "table_row",
        "expected_fragment": "| retry_backoff_ms | int | 250 | No |",
    },
    {
        "id": "Q2",
        "question": "In the v3 Client.send() code example, what keyword argument is passed alongside `payload` to demonstrate retry configuration?",
        "correct_sdk_version": "v3",
        "correct_page_id": "client-send",
        "correct_source_file": "v3/client-send.md",
        "correct_section": "Example",
        "known_answer": "retry_backoff_ms=250 (idempotency_key=\"order.created:ord_123\" is also passed).",
        "depends_on": "code_fence",
        "expected_fragment": "retry_backoff_ms=250,",
    },
    {
        "id": "Q3",
        "question": "In `Client.connect()` v3, what type is the `region` parameter and is it required?",
        "correct_sdk_version": "v3",
        "correct_page_id": "client-connect",
        "correct_source_file": "v3/client-connect.md",
        "correct_section": "Parameters",
        "known_answer": "str, Required: Yes.",
        "depends_on": "table_row",
        "expected_fragment": "| region | str | n/a | Yes |",
    },
    {
        "id": "Q4",
        "question": "What is the default `window_ms` value in `RateLimiter.configure()` v3?",
        "correct_sdk_version": "v3",
        "correct_page_id": "rate-limiter-configure",
        "correct_source_file": "v3/rate-limiter-configure.md",
        "correct_section": "Parameters",
        "known_answer": "60000",
        "depends_on": "table_row",
        "expected_fragment": "| window_ms | int | 60000 | No |",
    },
    {
        "id": "Q5",
        "question": "In the Webhooks.subscribe() v3 example, which HTTP header carries the HMAC signature on Nimbus's callback request?",
        "correct_sdk_version": "v3",
        "correct_page_id": "webhooks-subscribe",
        "correct_source_file": "v3/webhooks-subscribe.md",
        "correct_section": "Parameters / Example",
        "known_answer": "X-Nimbus-Signature",
        "depends_on": "code_fence",
        "expected_fragment": "X-Nimbus-Signature",
    },
    {
        "id": "Q6",
        "question": "What is the default `chunk_size_mb` for `BatchUploader.upload()` v3?",
        "correct_sdk_version": "v3",
        "correct_page_id": "batch-uploader-upload",
        "correct_source_file": "v3/batch-uploader-upload.md",
        "correct_section": "Parameters",
        "known_answer": "8",
        "depends_on": "table_row",
        "expected_fragment": "| chunk_size_mb | int | 8 | No |",
    },
    {
        "id": "Q7",
        "question": "What is the default `ttl_seconds` for `AuthManager.refresh_token()` v3, and what exception is raised when the refresh token has expired?",
        "correct_sdk_version": "v3",
        "correct_page_id": "auth-manager-refresh-token",
        "correct_source_file": "v3/auth-manager-refresh-token.md",
        "correct_section": "Parameters / Errors",
        "known_answer": "3600 seconds; raises TokenExpiredError.",
        "depends_on": "table_row",
        "expected_fragment": "| ttl_seconds | int | 3600 | No |",
    },
    {
        "id": "Q8",
        "question": "Does `RateLimiter.configure()` v2 support a `burst` parameter?",
        "correct_sdk_version": "v2",
        "correct_page_id": "rate-limiter-configure",
        "correct_source_file": "v2/rate-limiter-configure.md",
        "correct_section": "Parameters",
        "known_answer": "No -- v2 has no burst parameter (max_requests, window_ms only). burst=20 was added in v3.",
        "depends_on": "table_row",
        "expected_fragment": "There is no burst allowance in this version",
    },
]

# 6 of 8 questions are keyed to a parameter-table row; 2 are keyed to a
# fenced code sample. All 8 were written directly from the source pages
# before any retrieval was run.

OUT_OF_CORPUS_QUESTIONS = [
    {
        "id": "R1",
        "question": "What is the rate limit (requests per minute) for the /v3/analytics/export endpoint?",
        "why_unanswerable": "No analytics/export endpoint is documented anywhere in the 8 ingested pages.",
    },
    {
        "id": "R2",
        "question": "What error code does Client.send() return when the connection pool is exhausted?",
        "why_unanswerable": "Client.send()'s Errors section only documents PayloadValidationError and DeliveryTimeoutError -- no connection-pool error exists in the corpus.",
    },
    {
        "id": "R3",
        "question": "Does Nimbus SDK v3 support WebSocket streaming for real-time message delivery?",
        "why_unanswerable": "None of the 8 pages mention WebSockets or streaming; the documented transport is the blocking Client.send()/connect() pair only.",
    },
]
